### PR TITLE
Fix error when using Active Support 4.2

### PR DESCRIPTION
**Pull request by jonahb**
Fixes jayfajardo/openlibrary#20

### CODE REVIEW

**Comment by jonahb** [comment]
@jayfajardo Any chance of merging this?

**Comment by bhardin** [comment]
Wow. This is old. I have a similar problem. Maybe we should write a new library?

**Comment by jonahb** [comment]
@bhardin I don't want to bite that off right now, but maybe you'd like to fork and merge?

**Comment by jayfajardo** [comment]
sorry, merging your PR now.

**Comment by jonahb** [comment]
Thanks @jayfajardo

**Pull request merged**
